name: Publish zlib include files and static library
on:
  release:
    types:
      - published

env:
  ZLIB_VERSION: "1.3.1"

defaults:
  run:
    shell: bash

jobs:
  build-linux:
    name: linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [x86_64, aarch64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Fetch zlib code
        run: |
          git clone https://github.com/madler/zlib.git
          cd zlib
          git checkout v$ZLIB_VERSION
      - name: Build static library
        run: |
          cd $GITHUB_WORKSPACE/zlib
          mkdir build
          ./configure --prefix=$GITHUB_WORKSPACE/zlib/build --warn
          make -j2
          make install
      - name: Compress include files
        if: ${{ matrix.platform == 'x86_64' }}
        run: |
          cd $GITHUB_WORKSPACE/zlib/build
          tar -zcvf zlib-include.tar.gz -C include .
      - name: Compress static library
        run: |
          cd $GITHUB_WORKSPACE/zlib/build
          gzip -9 -c lib/libz.a > zlib-lib-${{ matrix.platform }}-unknown-linux-gnu.gz
      - name: Upload include files
        if: ${{ matrix.platform == 'x86_64' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ github.workspace }}/zlib/build/zlib-include.tar.gz
          asset_name: zlib-include.tar.gz
          asset_content_type: application/gzip
      - name: Upload static library
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ github.workspace }}/zlib/build/zlib-lib-${{ matrix.platform }}-unknown-linux-gnu.gz
          asset_name: zlib-lib-${{ matrix.platform }}-unknown-linux-gnu.gz
          asset_content_type: application/gzip

  build-windows:
    name: windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [x86_64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Fetch zlib code
        run: |
          git clone https://github.com/madler/zlib.git
          cd zlib
          git checkout v$ZLIB_VERSION
      - name: Build static library
        run: |
          cd $GITHUB_WORKSPACE/zlib
          cmake -S. -B build -D CMAKE_CONFIGURATION_TYPES="Release"
          cmake --build build --config Release
      - name: Compress static library
        run: |
          cd $GITHUB_WORKSPACE/zlib/build/Release
          ls ..
          ls
          mv zlibstatic.lib zlib.lib
          gzip -9 -c zlib.lib > zlib-lib-${{ matrix.platform }}-pc-windows-msvc.gz
      - name: Upload static library
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ github.workspace }}/zlib/build/zlib-lib-${{ matrix.platform }}-pc-windows-msvc.gz
          asset_name: zlib-lib-${{ matrix.platform }}-pc-windows-msvc.gz
          asset_content_type: application/gzip
