name: Publish zlib include and static library
on:
  release:
    types:
      - published

env:
  ZLIB_VERSION: "1.3.1"

defaults:
  run:
    shell: bash

jobs:
  build-linux:
    name: linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [x86_64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake
      - name: Fetch zlib code
        run: |
          git clone https://github.com/madler/zlib.git
          cd zlib
          git checkout v$ZLIB_VERSION
      - name: Configure cmake
        run: |
          mkdir build && cd build
          cmake ..
      - name: Build static library
        run: |
          make -C build
      - name: Compress include and static library
        run: |
          tar -zcvf zlib-include.tar.gz zlib.h zconf.h
          gzip -9 -c libz.a > zlib-lib-${{ matrix.platform }}-unknown-linux-gnu.gz
      - name: Upload include
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: zlib-include.tar.gz
          asset_name: zlib-include.tar.gz
          asset_content_type: application/gzip
      - name: Upload static library
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: zlib-lib-${{ matrix.platform }}-unknown-linux-gnu.gz
          asset_name: zlib-lib-${{ matrix.platform }}-unknown-linux-gnu.gz
          asset_content_type: application/gzip
